<script setup lang="ts">
import { onMounted, ref } from "vue";
import { createApiClient } from "../api/apiClient";
import { API_BASE_URL } from "../config";
import { AUTH_TOKEN_STORAGE_KEY } from "../authClient";
type Run = { runId: string; status: string; runName?: string; metrics?: Record<string, number> };
type CaseResult = { caseId: string; category: string; status: string; confirmed: boolean; evidenceTypes: string[] };
const api = createApiClient({ baseUrl: API_BASE_URL, getAccessToken: () => window.localStorage.getItem(AUTH_TOKEN_STORAGE_KEY) });
const runs = ref<Run[]>([]); const cases = ref<CaseResult[]>([]); const selected = ref<Run | null>(null); const loading = ref(false); const error = ref<string | null>(null);
const statusLabel = (value: unknown): string => ({ queued: "排队中", running: "执行中", completed: "已完成", failed: "失败" }[String(value)] ?? String(value));
const metricLabel = (value: string): string => ({ rootCauseAccuracy: "根因准确率", confirmationAccuracy: "确认准确率", toolSelectionAccuracy: "工具选择准确率", evidenceCoverage: "证据覆盖率", evidenceGroundedness: "证据关联性", toolSuccessRate: "工具成功率", averageSteps: "平均步骤数", averageToolCalls: "平均工具调用", failureRate: "失败率", latency: "平均耗时", verificationSuccessRate: "验证成功率", diagnosisVerifiedRate: "诊断验证率", patchApplySuccessRate: "补丁应用成功率", fixSuccessRate: "修复成功率", regressionTestPassRate: "回归测试通过率", averageRepairAttempts: "平均修复次数" }[value] ?? value);
async function refresh(): Promise<void> { const response = await api.request<{ items: Run[] }>("/evaluation/runs"); runs.value = response.items; }
async function createRun(): Promise<void> { loading.value = true; error.value = null; try { const response = await api.request<Run>("/evaluation/runs", { method: "POST", body: JSON.stringify({ run_name: `run-${Date.now()}`, prompt_version: "current", workflow_version: "ci-v1" }) }); selected.value = response; await refresh(); } catch (cause) { error.value = cause instanceof Error ? cause.message : "创建评测失败"; } finally { loading.value = false; } }
async function selectRun(run: Run): Promise<void> { selected.value = await api.request<Run>(`/evaluation/runs/${run.runId}`); const result = await api.request<{ items: CaseResult[] }>(`/evaluation/runs/${run.runId}/cases`); cases.value = result.items; }
onMounted(refresh);
</script>
<template><section class="evaluation"><p>DEVPILOT / 智能评测</p><h2>Agent 评测运行</h2><button :disabled="loading" @click="createRun">{{ loading ? "创建中…" : "创建评测任务" }}</button><p v-if="error" class="error">{{ error }}</p><div class="layout"><aside><h3>评测任务</h3><button v-for="run in runs" :key="run.runId" class="run" @click="selectRun(run)">{{ run.runName || run.runId }} · {{ statusLabel(run.status) }}</button><p v-if="!runs.length">暂无评测任务</p></aside><main v-if="selected"><h3>{{ selected.runName || selected.runId }} · {{ statusLabel(selected.status) }}</h3><div class="metrics"><span v-for="(value, key) in selected.metrics || {}" :key="key"><b>{{ metricLabel(String(key)) }}</b>{{ typeof value === "number" ? value.toFixed(3) : value }}</span></div><table v-if="cases.length"><thead><tr><th>案例</th><th>故障类别</th><th>状态</th><th>已确认</th><th>证据类型</th></tr></thead><tbody><tr v-for="item in cases" :key="item.caseId"><td>{{ item.caseId }}</td><td>{{ item.category }}</td><td>{{ statusLabel(item.status) }}</td><td>{{ item.confirmed ? "是" : "否" }}</td><td>{{ item.evidenceTypes.join(", ") }}</td></tr></tbody></table><p v-else>案例结果尚未生成，请稍后刷新任务。</p></main></div></section></template>
<style scoped>.evaluation{padding:2rem}.layout{display:grid;grid-template-columns:16rem 1fr;gap:2rem;margin-top:1.5rem}.run{display:block;width:100%;text-align:left;margin:.4rem 0;padding:.6rem}.metrics{display:flex;flex-wrap:wrap;gap:.6rem}.metrics span{display:grid;gap:.25rem;padding:.7rem;border:1px solid var(--line);border-radius:var(--radius-md)}table{width:100%;margin-top:1.5rem;border-collapse:collapse}th,td{padding:.55rem;border-bottom:1px solid var(--line);text-align:left}.error{color:#c33}@media(max-width:700px){.layout{grid-template-columns:1fr}}</style>
